import Link from "next/link";
import { capabilities, evidence, siteConfig, workPrinciples } from "@/content/site-content";

export default function Home() {
  return <>
    <section className="hero shell"><div className="hero-copy"><p className="eyebrow">Staff / Principal Software Engineer · Solutions Architect</p><h1>I build, repair, modernize, and explain difficult software systems.</h1><p className="lede">I’m Jason Pollard, a hands-on technical leader with 20+ years of experience. I use AI to move real engineering work forward—with human judgment governing security, maintainability, and architectural fit.</p><div className="actions"><Link className="button primary" href="/work">View selected work</Link><Link className="button" href="/ai-engineering">How I use AI</Link>{siteConfig.resumeUrl && <a className="button" href={siteConfig.resumeUrl} download>Download résumé</a>}<a className="button quiet" href={`mailto:${siteConfig.email}`}>Email Jason</a></div></div><aside className="hero-note" aria-label="Role and location"><span className="signal" aria-hidden="true" /><p>Available for the right remote U.S. role</p><strong>Staff engineering<br />Principal engineering<br />Solutions architecture</strong></aside></section>
    <section className="section shell"><div className="section-heading"><p className="eyebrow">What I bring</p><h2>Experienced engineering, close to the work.</h2></div><div className="three-grid">{capabilities.map((item, i) => <article className="numbered-card" key={item.title}><span>0{i + 1}</span><h3>{item.title}</h3><p>{item.text}</p></article>)}</div></section>
    <section className="section evidence-section"><div className="shell"><div className="section-heading"><p className="eyebrow">Selected evidence</p><h2>Outcomes, not adjectives.</h2></div><div className="evidence-grid">{evidence.map((item) => <div className="evidence" key={item.value}><strong>{item.value}</strong><p>{item.label}</p></div>)}</div><p className="context-note">Additional work spans architecture, cloud migrations, CI/CD, security, developer platforms, and legacy modernization.</p></div></section>
    <section className="section shell split"><div className="section-heading"><p className="eyebrow">How I work</p><h2>Make uncertainty visible. Reduce it deliberately.</h2><p>I keep technical direction connected to implementation and operations.</p></div><ol className="process-list">{workPrinciples.map((item, i) => <li key={item}><span>{String(i + 1).padStart(2, "0")}</span>{item}</li>)}</ol></section>
    <section className="section shell"><div className="link-panels"><Link href="/work"><span>Selected work</span><strong>Systems changed, risks reduced, delivery improved.</strong><b aria-hidden="true">↗</b></Link><Link href="/ai-engineering"><span>AI engineering</span><strong>Acceleration with a disciplined review loop.</strong><b aria-hidden="true">↗</b></Link><Link href="/projects"><span>Independent projects</span><strong>Curiosity expressed through working software.</strong><b aria-hidden="true">↗</b></Link></div><p className="personal-note">Independent projects give me room to explore product design, tooling, and unusual technical ideas—without asking the professional site to wear a neon costume.</p></section>
  </>;
}
